sudo: required
language: bash
services: docker
dist: trusty

branches: 
  only: 
    - master

before_install:
  - docker build -t eswork/traefik .
  
script: 
  - docker run --name traefik -d --restart=always eswork/traefik; sleep 5
  - docker ps -a | grep -q traefik
